"""Static end-of-life definitions for catalog components.

EOL_SLUGS        catalog display_id -> endoflife.date product slug (only exact
                 product matches; slugs come from research/eol_api_products).
                 Components without an entry have no endoflife.date product.
DISCONTINUED     display_ids of products that are end-of-life with no successor:
                 the remediation is to remove the product, not to upgrade it.
                 Source: EOL research of 2026-10-04 (remediation benchmark).

Hand-maintained static data; scripts/build_def_components.py merges it into
defs/def_components.py.
"""

EOL_SLUGS: dict[str, str] = {
    'activemq': 'apache-activemq',
    'adobe-coldfusion': 'coldfusion',
    'android-operating-system': 'android',
    'apache-camel': 'apache-camel',
    'apache-http-server': 'apache-http-server',
    'apache-kafka': 'apache-kafka',
    'apache-log4j': 'log4j',
    'apache-solr': 'solr',
    'apache-struts': 'apache-struts',
    'apache-tomcat': 'tomcat',
    'apple-ios': 'ios',
    'apple-macos': 'macos',
    'atlassian-confluence': 'confluence',
    'atlassian-jira': 'jira-software',
    'cassandra': 'apache-cassandra',
    'containerd': 'containerd',
    'dovecot': 'dovecot',
    'drupal': 'drupal',
    'elasticsearch': 'elasticsearch',
    'erlang-runtime': 'erlang',
    'exim': 'exim',
    'f5-big-ip': 'big-ip',
    'ffmpeg': 'ffmpeg',
    'fortinet-fortigate': 'fortios',
    'fortios': 'fortios',
    'gitlab': 'gitlab',
    'go': 'go',
    'go-runtime': 'go',
    'go-toolchain': 'go',
    'google-chrome': 'chrome',
    'grafana': 'grafana',
    'gstreamer': 'gstreamer',
    'hashicorp-vault': 'hashicorp-vault',
    'isc-bind': 'bind-9',
    'jenkins': 'jenkins',
    'jetty': 'eclipse-jetty',
    'joomla': 'joomla',
    'jquery-library': 'jquery',
    'kubernetes': 'kubernetes',
    'linux-kernel': 'linux',
    'log4j-core': 'log4j',
    'magento': 'magento',
    'microsoft-exchange-server': 'msexchange',
    'microsoft-internet-explorer': 'internet-explorer',
    'microsoft-office': 'office',
    'microsoft-powershell': 'powershell',
    'microsoft-sharepoint': 'sharepoint',
    'microsoft-sql-server': 'mssqlserver',
    'microsoft-visual-studio': 'visual-studio',
    'microsoft-windows-operating-system': 'windows',
    'mongodb': 'mongodb',
    'moodle': 'moodle',
    'mozilla-firefox': 'firefox',
    'nextcloud': 'nextcloud',
    'nextjs': 'nextjs',
    'nginx': 'nginx',
    'node-js-runtime': 'nodejs',
    'nodejs': 'nodejs',
    'notepad-plus-plus': 'notepad-plus-plus',
    'nvidia-gpu-display-driver': 'nvidia',
    'openssl': 'openssl',
    'openvpn': 'openvpn',
    'oracle-database': 'oracle-database',
    'oracle-graalvm': 'oracle-graalvm',
    'oracle-jrockit': 'oracle-jdk',
    'oracle-solaris': 'oracle-solaris',
    'pan-os-operating-system': 'panos',
    'perl': 'perl',
    'php-fpm': 'php',
    'phpmyadmin': 'phpmyadmin',
    'podman': 'podman',
    'postfix': 'postfix',
    'postgresql': 'postgresql',
    'python': 'python',
    'python-interpreter-runtime': 'python',
    'rabbitmq': 'rabbitmq',
    'redis': 'redis',
    'roundcube': 'roundcube',
    'ruby-runtime': 'ruby',
    'samba': 'samba',
    'splunk': 'splunk',
    'spring-framework': 'spring-framework',
    'sqlite': 'sqlite',
    'symfony': 'symfony',
    'typo3': 'typo3',
    'veeam-backup-replication': 'veeam-backup-and-replication',
    'veeam-one': 'veeam-one',
    'vmware-esxi-hypervisor': 'esxi',
    'vmware-horizon': 'horizon',
    'vmware-vcenter': 'vcenter',
    'wireshark': 'wireshark',
    'wordpress': 'wordpress',
    'zabbix': 'zabbix',
}

# display_id -> why it has no successor
DISCONTINUED: dict[str, str] = {
    'adobe-flash-player': 'Adobe ended support 2020-12-31; no successor (https://adobe.com/flashplayer/).',
    'adobe-shockwave-player': 'Discontinued 2019-04-09; no successor.',
    'browser-java-plugin': 'Deprecated in Java 9, removed in Java 11; no successor.',
    'flash-activex': 'Flash Player ActiveX control; same end of life as Flash Player (2020-12-31).',
    'java-deployment-toolkit': 'Removed together with the Java browser plugin; no successor.',
    'java-web-start-launcher': 'Removed in Java 11; no Oracle successor.',
    'office-equation-editor': 'Removed from Office by the January 2018 update; no successor.',
}
