"""Static catalog of software components for iteration."""

from dataclasses import dataclass
from enum import Enum


class Kind(Enum):
    """How a software component is deployed and patched."""

    APPLICATION = "application"
    LIBRARY = "library"
    RUNTIME_HOST = "runtime_host"
    OS = "os"


class OsSubtype(Enum):
    """Subtype used only when kind is OS.
    - GPOS for general-purpose systems (Windows, Linux, macOS, and their in-box kernel and platform
    parts) 
    - OTITOS for network-appliance and OT systems.
    """

    GPOS = "GPOS"
    OTITOS = "OTITOS"


@dataclass(frozen=True, slots=True)
class SoftwareComponent:
    """One named component and its classification.

    os_subtype is set only for operating systems: GPOS for general-purpose
    systems (Windows, Linux, macOS, and their in-box kernel and platform
    parts) and OTITOS for network-appliance and OT systems.
    """

    name: str
    kind: Kind
    os_subtype: OsSubtype | None = None

    def __post_init__(self) -> None:
        if self.kind is Kind.OS and self.os_subtype is None:
            raise ValueError(f"{self.name} is an OS and needs a subtype")
        if self.kind is not Kind.OS and self.os_subtype is not None:
            raise ValueError(f"{self.name} is not an OS and has a subtype")


SOFTWARE_COMPONENTS: tuple[SoftwareComponent, ...] = (
    SoftwareComponent("7-zip", Kind.APPLICATION),
    SoftwareComponent("abrt-automatic-bug-reporting-tool", Kind.APPLICATION),
    SoftwareComponent("acl", Kind.LIBRARY),
    SoftwareComponent("active-directory-certificate-services-ad-cs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("active-directory-domain-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("active-directory-federation-services-ad-fs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("activemq", Kind.APPLICATION),
    SoftwareComponent("adobe-acrobat", Kind.APPLICATION),
    SoftwareComponent("adobe-flash-player", Kind.LIBRARY),
    SoftwareComponent("adobe-graphics-manager-library-agm", Kind.LIBRARY),
    SoftwareComponent("adobe-pdf-browser-plugin", Kind.LIBRARY),
    SoftwareComponent("adobe-shockwave-player", Kind.LIBRARY),
    SoftwareComponent("aide", Kind.APPLICATION),
    SoftwareComponent("amd-zen-processor", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("android-operating-system", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("android-system-webview", Kind.RUNTIME_HOST),
    SoftwareComponent("angle-graphics-library", Kind.LIBRARY),
    SoftwareComponent("apache-chainsaw-gui-log-viewer", Kind.APPLICATION),
    SoftwareComponent("apache-commons-configuration", Kind.LIBRARY),
    SoftwareComponent("apache-commons-fileupload", Kind.LIBRARY),
    SoftwareComponent("apache-commons-lang", Kind.LIBRARY),
    SoftwareComponent("apache-commons-text", Kind.LIBRARY),
    SoftwareComponent("apache-derby", Kind.LIBRARY),
    SoftwareComponent("apache-http-server", Kind.APPLICATION),
    SoftwareComponent("apache-log4j", Kind.LIBRARY),
    SoftwareComponent("apache-mod-cgi", Kind.LIBRARY),
    SoftwareComponent("apache-mod-dav", Kind.LIBRARY),
    SoftwareComponent("apache-mod-dav-fs", Kind.LIBRARY),
    SoftwareComponent("apache-mod-dav-lock", Kind.LIBRARY),
    SoftwareComponent("apache-mod-http2", Kind.LIBRARY),
    SoftwareComponent("apache-mod-ldap", Kind.LIBRARY),
    SoftwareComponent("apache-mod-lua", Kind.LIBRARY),
    SoftwareComponent("apache-mod-macro", Kind.LIBRARY),
    SoftwareComponent("apache-mod-mime", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-ajp", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-ftp", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-html", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-http2", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-uwsgi", Kind.LIBRARY),
    SoftwareComponent("apache-mod-proxy-wstunnel", Kind.LIBRARY),
    SoftwareComponent("apache-mod-remoteip", Kind.LIBRARY),
    SoftwareComponent("apache-mod-rewrite", Kind.LIBRARY),
    SoftwareComponent("apache-mod-sed", Kind.LIBRARY),
    SoftwareComponent("apache-mod-session", Kind.LIBRARY),
    SoftwareComponent("apache-mod-ssl", Kind.LIBRARY),
    SoftwareComponent("apache-mod-xml2enc", Kind.LIBRARY),
    SoftwareComponent("apache-tomcat", Kind.APPLICATION),
    SoftwareComponent("apache-tomcat-native-library", Kind.LIBRARY),
    SoftwareComponent("apache-tomcat-windows-installer", Kind.APPLICATION),
    SoftwareComponent("apple-afp-client-afpfs-kernel-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-apfs-filesystem", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-authkit-framework", Kind.LIBRARY),
    SoftwareComponent("apple-calendar", Kind.APPLICATION),
    SoftwareComponent("apple-contacts-framework", Kind.LIBRARY),
    SoftwareComponent("apple-coremedia", Kind.LIBRARY),
    SoftwareComponent("apple-coreservices", Kind.LIBRARY),
    SoftwareComponent("apple-dcerpc", Kind.LIBRARY),
    SoftwareComponent("apple-disk-images-diskimages-subsystem", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-driverkit-framework", Kind.LIBRARY),
    SoftwareComponent("apple-game-center", Kind.APPLICATION),
    SoftwareComponent("apple-garageband", Kind.APPLICATION),
    SoftwareComponent("apple-hfs-filesystem", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-imageio", Kind.LIBRARY),
    SoftwareComponent("apple-iokit-framework", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-iomobileframebuffer", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-ios", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-iso-9660-filesystem", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-libinfo", Kind.LIBRARY),
    SoftwareComponent("apple-libresolv", Kind.LIBRARY),
    SoftwareComponent("apple-macos", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-macos-gpu-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-macos-wi-fi-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-maps", Kind.APPLICATION),
    SoftwareComponent("apple-model-io", Kind.LIBRARY),
    SoftwareComponent("apple-neural-engine", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-prores-component", Kind.LIBRARY),
    SoftwareComponent("apple-remote-events", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("apple-xnu-kernel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("appx-deployment-service-appxsvc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("arm64-cpu-architecture", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("arm64-sme-support", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("arm-neoverse-cortex-cpu", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("armv7-a-arm32-cpu-without-hardware-integer-divide", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("asp-net-core", Kind.RUNTIME_HOST),
    SoftwareComponent("assertj-core", Kind.LIBRARY),
    SoftwareComponent("attr", Kind.LIBRARY),
    SoftwareComponent("browser-extension-using-identity-api", Kind.LIBRARY),
    SoftwareComponent("browser-extension-using-native-messaging", Kind.LIBRARY),
    SoftwareComponent("browser-java-plugin", Kind.LIBRARY),
    SoftwareComponent("cairo-graphics-library", Kind.LIBRARY),
    SoftwareComponent("chrome-chromeos-image-burner-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("chromeos", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("chromeos-audio-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("chromeos-cryptohome", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("chrome-os-shell-ash", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("chromium-based-browser-updater", Kind.APPLICATION),
    SoftwareComponent("chromium-blink-rendering-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("chromium-browser", Kind.APPLICATION),
    SoftwareComponent("chromium-cast-chromecast-component", Kind.LIBRARY),
    SoftwareComponent("chromium-mojo-ipc", Kind.LIBRARY),
    SoftwareComponent("chromium-v8", Kind.RUNTIME_HOST),
    SoftwareComponent("cisco-discovery-protocol", Kind.LIBRARY),
    SoftwareComponent("cisco-jabber", Kind.APPLICATION),
    SoftwareComponent("cisco-nx-os-cli", Kind.OS, OsSubtype.OTITOS),
    SoftwareComponent("color-enhancer-browser-extension", Kind.LIBRARY),
    SoftwareComponent("connectwise-screenconnect-client", Kind.APPLICATION),
    SoftwareComponent("cros-disks-daemon", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("cups-browsed-service", Kind.APPLICATION),
    SoftwareComponent("cups-printing-system", Kind.APPLICATION),
    SoftwareComponent("curl-libcurl", Kind.LIBRARY),
    SoftwareComponent("dell-dbutil-2-3-sys", Kind.LIBRARY),
    SoftwareComponent("dell-supportassist", Kind.APPLICATION),
    SoftwareComponent("dnsmasq", Kind.APPLICATION),
    SoftwareComponent("dnssec-validating-dns-resolver", Kind.APPLICATION),
    SoftwareComponent("dolby-udc", Kind.LIBRARY),
    SoftwareComponent("dracut", Kind.APPLICATION),
    SoftwareComponent("eclipse-openj9", Kind.RUNTIME_HOST),
    SoftwareComponent("ecpg-postgresql-embedded-sql-c-preprocessor-library", Kind.LIBRARY),
    SoftwareComponent("erlang-ssh", Kind.LIBRARY),
    SoftwareComponent("escargot", Kind.RUNTIME_HOST),
    SoftwareComponent("expat", Kind.LIBRARY),
    SoftwareComponent("factorytalk-service-platform", Kind.APPLICATION),
    SoftwareComponent("ffmpeg", Kind.LIBRARY),
    SoftwareComponent("flash-activex", Kind.LIBRARY),
    SoftwareComponent("foomatic-rip-print-filter", Kind.APPLICATION),
    SoftwareComponent("fortinet-fortigate", Kind.OS, OsSubtype.OTITOS),
    SoftwareComponent("fortios", Kind.OS, OsSubtype.OTITOS),
    SoftwareComponent("freerdp", Kind.LIBRARY),
    SoftwareComponent("freetype", Kind.LIBRARY),
    SoftwareComponent("ghostscript", Kind.RUNTIME_HOST),
    SoftwareComponent("giflib", Kind.LIBRARY),
    SoftwareComponent("git", Kind.APPLICATION),
    SoftwareComponent("github-copilot-for-visual-studio-code", Kind.LIBRARY),
    SoftwareComponent("github-plugin-for-ide", Kind.LIBRARY),
    SoftwareComponent("git-or-mercurial-client", Kind.APPLICATION),
    SoftwareComponent("gix-date", Kind.LIBRARY),
    SoftwareComponent("glib", Kind.LIBRARY),
    SoftwareComponent("glibc", Kind.LIBRARY),
    SoftwareComponent("gnutls", Kind.LIBRARY),
    SoftwareComponent("gnu-wget", Kind.APPLICATION),
    SoftwareComponent("go", Kind.RUNTIME_HOST),
    SoftwareComponent("go-git", Kind.LIBRARY),
    SoftwareComponent("go-http2-client", Kind.LIBRARY),
    SoftwareComponent("golang-org-x-crypto-ssh-library", Kind.LIBRARY),
    SoftwareComponent("golang-x-text", Kind.LIBRARY),
    SoftwareComponent("go-net-http-server", Kind.LIBRARY),
    SoftwareComponent("google-chrome", Kind.APPLICATION),
    SoftwareComponent("google-chrome-credentialprovider", Kind.LIBRARY),
    SoftwareComponent("google-chrome-for-android", Kind.APPLICATION),
    SoftwareComponent("google-chrome-for-ios", Kind.APPLICATION),
    SoftwareComponent("google-chrome-updater", Kind.APPLICATION),
    SoftwareComponent("google-dawn", Kind.LIBRARY),
    SoftwareComponent("google-skia", Kind.LIBRARY),
    SoftwareComponent("google-tint-webgpu-shading-language-compiler", Kind.LIBRARY),
    SoftwareComponent("go-runtime", Kind.RUNTIME_HOST),
    SoftwareComponent("go-standard-library-encoding-asn1-package", Kind.LIBRARY),
    SoftwareComponent("go-standard-library-net-url-package", Kind.LIBRARY),
    SoftwareComponent("go-toolchain", Kind.APPLICATION),
    SoftwareComponent("gpu-graphics-driver-stack", Kind.LIBRARY),
    SoftwareComponent("graphite2", Kind.LIBRARY),
    SoftwareComponent("grpc-go-server-library", Kind.LIBRARY),
    SoftwareComponent("gson", Kind.LIBRARY),
    SoftwareComponent("gstreamer", Kind.LIBRARY),
    SoftwareComponent("gstreamer-dtls", Kind.LIBRARY),
    SoftwareComponent("gstreamer-gdkpixbuf", Kind.LIBRARY),
    SoftwareComponent("gstreamer-isomp4", Kind.LIBRARY),
    SoftwareComponent("gstreamer-plugins-bad", Kind.LIBRARY),
    SoftwareComponent("gstreamer-plugins-base", Kind.LIBRARY),
    SoftwareComponent("gstreamer-plugins-good", Kind.LIBRARY),
    SoftwareComponent("gstreamer-qtmoovrecover", Kind.LIBRARY),
    SoftwareComponent("gstreamer-rfbsrc", Kind.LIBRARY),
    SoftwareComponent("gstreamer-rtpsbcdepay", Kind.LIBRARY),
    SoftwareComponent("gstreamer-vmnc", Kind.LIBRARY),
    SoftwareComponent("gstreamer-wavpack", Kind.LIBRARY),
    SoftwareComponent("gstreamer-wavparse", Kind.LIBRARY),
    SoftwareComponent("gvim", Kind.APPLICATION),
    SoftwareComponent("gzip", Kind.APPLICATION),
    SoftwareComponent("harfbuzz", Kind.LIBRARY),
    SoftwareComponent("hashicorp-vagrant", Kind.APPLICATION),
    SoftwareComponent("http-2-protocol-implementation", Kind.LIBRARY),
    SoftwareComponent("hutool", Kind.LIBRARY),
    SoftwareComponent("ibm-planning-analytics", Kind.APPLICATION),
    SoftwareComponent("ibm-sdk-java-orb", Kind.LIBRARY),
    SoftwareComponent("ibm-sdk-java-technology-edition", Kind.RUNTIME_HOST),
    SoftwareComponent("icu-international-components-for-unicode-library", Kind.LIBRARY),
    SoftwareComponent("image-size", Kind.LIBRARY),
    SoftwareComponent("intel-oneapi-mkl", Kind.LIBRARY),
    SoftwareComponent("intel-processor", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("isc-bind", Kind.APPLICATION),
    SoftwareComponent("jackson-databind", Kind.LIBRARY),
    SoftwareComponent("java-2d", Kind.LIBRARY),
    SoftwareComponent("java-deployment-toolkit", Kind.LIBRARY),
    SoftwareComponent("javadoc", Kind.APPLICATION),
    SoftwareComponent("javafx", Kind.LIBRARY),
    SoftwareComponent("java-hotspot", Kind.RUNTIME_HOST),
    SoftwareComponent("java-jce", Kind.LIBRARY),
    SoftwareComponent("java-jgss", Kind.LIBRARY),
    SoftwareComponent("java-jndi", Kind.LIBRARY),
    SoftwareComponent("java-nashorn", Kind.RUNTIME_HOST),
    SoftwareComponent("java-se", Kind.RUNTIME_HOST),
    SoftwareComponent("java-web-start-launcher", Kind.APPLICATION),
    SoftwareComponent("jenkins", Kind.APPLICATION),
    SoftwareComponent("jetbrains-intellij-idea", Kind.APPLICATION),
    SoftwareComponent("jquery-library", Kind.LIBRARY),
    SoftwareComponent("js-yaml", Kind.LIBRARY),
    SoftwareComponent("junit-4", Kind.LIBRARY),
    SoftwareComponent("kaltura-html5", Kind.LIBRARY),
    SoftwareComponent("keytool", Kind.APPLICATION),
    SoftwareComponent("libacl", Kind.LIBRARY),
    SoftwareComponent("libarchive", Kind.LIBRARY),
    SoftwareComponent("libc-glibc", Kind.LIBRARY),
    SoftwareComponent("libcupsfilters", Kind.LIBRARY),
    SoftwareComponent("libjpeg", Kind.LIBRARY),
    SoftwareComponent("libpng", Kind.LIBRARY),
    SoftwareComponent("libppd-ppd-from-ipp-library", Kind.LIBRARY),
    SoftwareComponent("libpq-postgresql-c-client-library", Kind.LIBRARY),
    SoftwareComponent("libsolv", Kind.LIBRARY),
    SoftwareComponent("libssh", Kind.LIBRARY),
    SoftwareComponent("libtasn1", Kind.LIBRARY),
    SoftwareComponent("libtiff", Kind.LIBRARY),
    SoftwareComponent("libvorbis", Kind.LIBRARY),
    SoftwareComponent("libvpx", Kind.LIBRARY),
    SoftwareComponent("libvterm-terminal-emulation-library", Kind.LIBRARY),
    SoftwareComponent("libwebp", Kind.LIBRARY),
    SoftwareComponent("libwebrtc", Kind.LIBRARY),
    SoftwareComponent("libxfont2", Kind.LIBRARY),
    SoftwareComponent("libxml2", Kind.LIBRARY),
    SoftwareComponent("libyuv", Kind.LIBRARY),
    SoftwareComponent("linux-act-csum", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-act-ct", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-act-pedit", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-algif-hash", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-alsa", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-alsa-aloop-loopback", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-asymmetric-keys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-atm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-atm-clip", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-atm-lec", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-batman-adv", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-bluetooth", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-bonding", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-bpf", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-brcmfmac", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-bridge", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-btrfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-calipso", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-can", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-can-bcm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ccp-crypto", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ch9200-usb-to", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-chromeos-operating-system", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-cifs-smb-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-cls-u32", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-coretemp", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-crypto", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-dccp", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-dlm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-dm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm-amdgpu", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm-i915", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm-sched", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm-vkms", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-drm-vmwgfx", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ebtables", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-efivarfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ext4", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-f2fs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-fbdev", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-fsl-mc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ftrace", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-geneve", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-gfs2", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-hid", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-hv-netvsc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-i2c", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-i40e", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ib-hfi1", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ib-umad", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ice", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-idpf", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ieee802154", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-iio", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ima", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-imon", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-iomap", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-iommu-sva", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ip6t-eui64", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ip6-tunnel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ipset", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ish-hid", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-iw-cm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-iwlwifi", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-kernel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-kernel-af-alg", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-kernel-intel-ixgbevf-network-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-keys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ktls", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-kvm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-libceph", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-lio-iscsi-target", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-lpfc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-macvlan", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-memcg", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-mlx4", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-mlxsw", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-mwifiex", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nbd", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-ndisc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-netdevsim", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-netfilter", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-net-mlx5", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-net-sched", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-networking", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nf-conntrack", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nf-conntrack-h323", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nf-conntrack-sip", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nfnetlink-cthelper", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nfsd", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nilfs2", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nouveau", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nvme", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nvme-fc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nvmet-fc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nvmet-rdma", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-nvmet-tcp", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-operating-system", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-page-pool", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-pam", Kind.LIBRARY),
    SoftwareComponent("linux-pci-endpoint-configfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-procfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-qla2xxx", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-qmi-wwan", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rdma", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rdma-mana", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rdma-rxe", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rds", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rmi4", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-romfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rtsx-usb-ms", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rtw89", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-rxrpc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-sch-ets", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-sch-hfsc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-sch-teql", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-scpi", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-scsi", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-sctp", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-selinux", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-siw", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-smc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-smc91x", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-snd-6fire", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-snd-firewire-motu", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-snd-usb-audio", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-squashfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-sysv-ipc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-tipc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-udf", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-um", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-usb", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-usbnet", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-usb-storage", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-uvcvideo", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-virtio-crypto", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-vmw-pvrdma", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-vmw-vmci", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-vsock", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-vxcan", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-wacom", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-wifi", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-xen", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-xen-privcmd", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-xfrm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-xfs", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("linux-zram", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("little-cms-lcms2-color-management-library", Kind.LIBRARY),
    SoftwareComponent("log4j-core", Kind.LIBRARY),
    SoftwareComponent("lsass", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("lz4", Kind.LIBRARY),
    SoftwareComponent("macos-screen-sharing-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("macos-smb-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("malicious-browser-extension-installed", Kind.LIBRARY),
    SoftwareComponent("mariadb-mysql", Kind.APPLICATION),
    SoftwareComponent("mcp-java-sdk", Kind.LIBRARY),
    SoftwareComponent("mesa-3d-graphics-library", Kind.LIBRARY),
    SoftwareComponent("micronaut-json-core", Kind.LIBRARY),
    SoftwareComponent("microsoft-ado", Kind.LIBRARY),
    SoftwareComponent("microsoft-chakra-scripting-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-com-for-windows", Kind.LIBRARY),
    SoftwareComponent("microsoft-compiled-html-help-viewer-hh-exe", Kind.APPLICATION),
    SoftwareComponent("microsoft-defender", Kind.APPLICATION),
    SoftwareComponent("microsoft-defender-antimalware-platform", Kind.APPLICATION),
    SoftwareComponent("microsoft-diasymreader-native-msdia-pdb-reader", Kind.LIBRARY),
    SoftwareComponent("microsoft-dotnet", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-edge", Kind.APPLICATION),
    SoftwareComponent("microsoft-edge-legacy-edgehtml", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-edge-webview2", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-excel", Kind.APPLICATION),
    SoftwareComponent("microsoft-exchange-server", Kind.APPLICATION),
    SoftwareComponent("microsoft-hyper-v", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-iis", Kind.APPLICATION),
    SoftwareComponent("microsoft-internet-explorer", Kind.APPLICATION),
    SoftwareComponent("microsoft-malware-protection-engine", Kind.LIBRARY),
    SoftwareComponent("microsoft-management-console", Kind.APPLICATION),
    SoftwareComponent("microsoft-message-queuing-msmq", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-mshtml-trident", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-network-device-enrollment-service-ndes-scep", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-odbc-driver", Kind.LIBRARY),
    SoftwareComponent("microsoft-office", Kind.APPLICATION),
    SoftwareComponent("microsoft-office-graphics-component", Kind.LIBRARY),
    SoftwareComponent("microsoft-ole-db-driver-for-sql-server", Kind.LIBRARY),
    SoftwareComponent("microsoft-outlook", Kind.APPLICATION),
    SoftwareComponent("microsoft-paint", Kind.APPLICATION),
    SoftwareComponent("microsoft-powerpoint", Kind.APPLICATION),
    SoftwareComponent("microsoft-powershell", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-quic", Kind.LIBRARY),
    SoftwareComponent("microsoft-sharepoint", Kind.APPLICATION),
    SoftwareComponent("microsoft-skype-for-business", Kind.APPLICATION),
    SoftwareComponent("microsoft-smbv1-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-sqlclient-data-provider", Kind.LIBRARY),
    SoftwareComponent("microsoft-sqlcmd", Kind.APPLICATION),
    SoftwareComponent("microsoft-sql-server", Kind.APPLICATION),
    SoftwareComponent("microsoft-teams", Kind.APPLICATION),
    SoftwareComponent("microsoft-visual-studio", Kind.APPLICATION),
    SoftwareComponent("microsoft-win32k", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-adobe-type-manager-library", Kind.LIBRARY),
    SoftwareComponent("microsoft-windows-ancillary-function-driver-for-winsock", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-certificate-dialog-uac", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-cifs-browser-protocol-driver-bowser-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-dhcp-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-dhcp-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-distributed-file-system-dfs-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-dns-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-dns-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-jet-database-engine", Kind.LIBRARY),
    SoftwareComponent("microsoft-windows-kernel-graphics-component-splwow64", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-layer-2-bridge-network-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-netbt-netbios-over-tcp-ip-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-network-policy-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-nfs-oncrpc-xdr-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-nfs-portmapper", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-nfs-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-operating-system", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-pgm", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-postscript-pcl6-class-printer-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-scripting-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-windows-script-runtime", Kind.RUNTIME_HOST),
    SoftwareComponent("microsoft-windows-shell", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-smb-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-smb-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-smb-witness-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-structuredquery-component", Kind.LIBRARY),
    SoftwareComponent("microsoft-windows-support-diagnostic-tool-msdt", Kind.APPLICATION),
    SoftwareComponent("microsoft-windows-tcp-ip-stack", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-telnet-client", Kind.APPLICATION),
    SoftwareComponent("microsoft-windows-themes", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-windows-winsock-ifs-layer-driver-ws2ifsl-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("microsoft-word", Kind.APPLICATION),
    SoftwareComponent("microsoft-xml-core-services-msxml", Kind.LIBRARY),
    SoftwareComponent("mod-auth-digest", Kind.LIBRARY),
    SoftwareComponent("mod-md", Kind.LIBRARY),
    SoftwareComponent("mongodb", Kind.APPLICATION),
    SoftwareComponent("motorola-sm56-modem-wdm-driver", Kind.LIBRARY),
    SoftwareComponent("mozilla-firefox", Kind.APPLICATION),
    SoftwareComponent("mozilla-firefox-focus-android", Kind.APPLICATION),
    SoftwareComponent("mozilla-firefox-for-android", Kind.APPLICATION),
    SoftwareComponent("mozilla-firefox-updater", Kind.APPLICATION),
    SoftwareComponent("mozilla-gecko-based-application-firefox-thunderbird", Kind.APPLICATION),
    SoftwareComponent("msgpack-python", Kind.LIBRARY),
    SoftwareComponent("mssql-extension-for-visual-studio-code", Kind.LIBRARY),
    SoftwareComponent("native-messaging-host", Kind.APPLICATION),
    SoftwareComponent("net-system-io-packaging-library", Kind.LIBRARY),
    SoftwareComponent("netty-codec-http", Kind.LIBRARY),
    SoftwareComponent("network-security-services-nss", Kind.LIBRARY),
    SoftwareComponent("nextjs", Kind.LIBRARY),
    SoftwareComponent("nodejs", Kind.RUNTIME_HOST),
    SoftwareComponent("node-js-built-in-http-https-proxy-tunnel-client", Kind.LIBRARY),
    SoftwareComponent("node-js-runtime", Kind.RUNTIME_HOST),
    SoftwareComponent("node-tar-npm-tar-package", Kind.LIBRARY),
    SoftwareComponent("nokogiri", Kind.LIBRARY),
    SoftwareComponent("notepad-plus-plus", Kind.APPLICATION),
    SoftwareComponent("nvidia-gpu-display-driver", Kind.LIBRARY),
    SoftwareComponent("office-equation-editor", Kind.LIBRARY),
    SoftwareComponent("open-iscsi", Kind.APPLICATION),
    SoftwareComponent("openssh", Kind.APPLICATION),
    SoftwareComponent("openssh-for-windows", Kind.APPLICATION),
    SoftwareComponent("openssl", Kind.LIBRARY),
    SoftwareComponent("openssl-quic-implementation-libssl", Kind.LIBRARY),
    SoftwareComponent("oracle-clusterware", Kind.APPLICATION),
    SoftwareComponent("oracle-coherence", Kind.APPLICATION),
    SoftwareComponent("oracle-cost-management", Kind.APPLICATION),
    SoftwareComponent("oracle-database", Kind.APPLICATION),
    SoftwareComponent("oracle-database-jdbc", Kind.LIBRARY),
    SoftwareComponent("oracle-database-ojvm", Kind.RUNTIME_HOST),
    SoftwareComponent("oracle-database-xdb", Kind.LIBRARY),
    SoftwareComponent("oracle-essbase", Kind.APPLICATION),
    SoftwareComponent("oracle-graalvm", Kind.RUNTIME_HOST),
    SoftwareComponent("oracle-identity-manager", Kind.APPLICATION),
    SoftwareComponent("oracle-java-advanced-management-console", Kind.APPLICATION),
    SoftwareComponent("oracle-java-mission-control", Kind.APPLICATION),
    SoftwareComponent("oracle-java-se-installer", Kind.APPLICATION),
    SoftwareComponent("oracle-jrockit", Kind.RUNTIME_HOST),
    SoftwareComponent("oracle-net-cman", Kind.APPLICATION),
    SoftwareComponent("oracle-solaris", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("oracle-weblogic", Kind.APPLICATION),
    SoftwareComponent("pcre", Kind.LIBRARY),
    SoftwareComponent("pcre2", Kind.LIBRARY),
    SoftwareComponent("pdfium-pdf-rendering-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("pdf-js-javascript-pdf-renderer", Kind.LIBRARY),
    SoftwareComponent("perl", Kind.RUNTIME_HOST),
    SoftwareComponent("perl-archive-tar", Kind.LIBRARY),
    SoftwareComponent("perl-dbi", Kind.LIBRARY),
    SoftwareComponent("perl-io-compress", Kind.LIBRARY),
    SoftwareComponent("pgadmin", Kind.APPLICATION),
    SoftwareComponent("php-fpm", Kind.RUNTIME_HOST),
    SoftwareComponent("plc-controller-firmware", Kind.OS, OsSubtype.OTITOS),
    SoftwareComponent("podman", Kind.APPLICATION),
    SoftwareComponent("polkit", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("poppler", Kind.LIBRARY),
    SoftwareComponent("postfix", Kind.APPLICATION),
    SoftwareComponent("postgresql", Kind.APPLICATION),
    SoftwareComponent("postgresql-pg-basebackup", Kind.APPLICATION),
    SoftwareComponent("postgresql-pg-dump", Kind.APPLICATION),
    SoftwareComponent("postgresql-pljava", Kind.LIBRARY),
    SoftwareComponent("postgresql-psql-interactive-terminal-client", Kind.APPLICATION),
    SoftwareComponent("postgresql-windows-installer", Kind.APPLICATION),
    SoftwareComponent("protobuf-go", Kind.LIBRARY),
    SoftwareComponent("putty-ssh-client", Kind.APPLICATION),
    SoftwareComponent("python", Kind.RUNTIME_HOST),
    SoftwareComponent("python-cryptography", Kind.LIBRARY),
    SoftwareComponent("python-html-parser", Kind.LIBRARY),
    SoftwareComponent("python-http-client", Kind.LIBRARY),
    SoftwareComponent("python-http-cookies", Kind.LIBRARY),
    SoftwareComponent("python-interpreter-runtime", Kind.RUNTIME_HOST),
    SoftwareComponent("qemu-hardware-emulator", Kind.RUNTIME_HOST),
    SoftwareComponent("radius", Kind.APPLICATION),
    SoftwareComponent("remote-desktop-client", Kind.APPLICATION),
    SoftwareComponent("rsync", Kind.APPLICATION),
    SoftwareComponent("runc", Kind.RUNTIME_HOST),
    SoftwareComponent("rust-openssl", Kind.LIBRARY),
    SoftwareComponent("samba", Kind.APPLICATION),
    SoftwareComponent("samba-dcerpcd", Kind.APPLICATION),
    SoftwareComponent("seunshare", Kind.APPLICATION),
    SoftwareComponent("sg3-utils", Kind.APPLICATION),
    SoftwareComponent("shamaton-msgpack", Kind.LIBRARY),
    SoftwareComponent("shlex", Kind.LIBRARY),
    SoftwareComponent("spidermonkey-javascript-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("splunk-cli", Kind.APPLICATION),
    SoftwareComponent("spring-framework", Kind.LIBRARY),
    SoftwareComponent("sqlite", Kind.LIBRARY),
    SoftwareComponent("sql-server-integration-services-visual-studio-extension", Kind.LIBRARY),
    SoftwareComponent("sql-server-native-client", Kind.LIBRARY),
    SoftwareComponent("ssh-library-application", Kind.APPLICATION),
    SoftwareComponent("ssh-server-built-on-the-ssh-library", Kind.APPLICATION),
    SoftwareComponent("ssri-library", Kind.LIBRARY),
    SoftwareComponent("sssd", Kind.APPLICATION),
    SoftwareComponent("sudo", Kind.APPLICATION),
    SoftwareComponent("swiftshader", Kind.LIBRARY),
    SoftwareComponent("system-text-encodings-web", Kind.LIBRARY),
    SoftwareComponent("tar-archive-processing-application", Kind.APPLICATION),
    SoftwareComponent("teamviewer-remote-client-host", Kind.APPLICATION),
    SoftwareComponent("tightvnc-server", Kind.APPLICATION),
    SoftwareComponent("tightvnc-viewer", Kind.APPLICATION),
    SoftwareComponent("tls-capable-process", Kind.APPLICATION),
    SoftwareComponent("tpm-2-0-reference-implementation", Kind.LIBRARY),
    SoftwareComponent("ubiquiti-unifi-network-application", Kind.APPLICATION),
    SoftwareComponent("udev", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("ultravnc", Kind.APPLICATION),
    SoftwareComponent("unbound", Kind.APPLICATION),
    SoftwareComponent("urllib3", Kind.LIBRARY),
    SoftwareComponent("usrsctp", Kind.LIBRARY),
    SoftwareComponent("veeam-backup-replication", Kind.APPLICATION),
    SoftwareComponent("veeam-one", Kind.APPLICATION),
    SoftwareComponent("vim", Kind.APPLICATION),
    SoftwareComponent("vim-xxd", Kind.APPLICATION),
    SoftwareComponent("visual-studio-code", Kind.APPLICATION),
    SoftwareComponent("visual-studio-installer", Kind.APPLICATION),
    SoftwareComponent("vlc-media-player", Kind.APPLICATION),
    SoftwareComponent("vmware-tools-open-vm-tools", Kind.APPLICATION),
    SoftwareComponent("wdac-ole-db-provider", Kind.LIBRARY),
    SoftwareComponent("web-browser-with-javascript-engine", Kind.APPLICATION),
    SoftwareComponent("webkit", Kind.RUNTIME_HOST),
    SoftwareComponent("webkitgtk", Kind.RUNTIME_HOST),
    SoftwareComponent("webrtc-gmp-h-264-video-decoder", Kind.LIBRARY),
    SoftwareComponent("windows-advanced-local-procedure-call-alpc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-alljoyn-api", Kind.LIBRARY),
    SoftwareComponent("windows-applocker-driver-appid-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-app-store", Kind.APPLICATION),
    SoftwareComponent("windows-bitlocker", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-bits", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-bluetooth-a2dp-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-bluetooth-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-branchcache", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-cloud-files-mini-filter-driver-cldflt-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-codecs-library", Kind.LIBRARY),
    SoftwareComponent("windows-comctl32", Kind.LIBRARY),
    SoftwareComponent("windows-common-log-file-system-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-core-messaging", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-cryptographic-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-data-dll-component", Kind.LIBRARY),
    SoftwareComponent("windows-defender-signature-update-stub-mpsigstub", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-deployment-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-device-health-attestation-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-digest-authentication", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-directshow", Kind.LIBRARY),
    SoftwareComponent("windows-directx", Kind.LIBRARY),
    SoftwareComponent("windows-dns-server-management-snap-in", Kind.APPLICATION),
    SoftwareComponent("windows-encrypting-file-system", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-enterprise-app-management-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-error-reporting", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-event-log-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-failover-cluster", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-fax-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-file-history-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-filtering-platform", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-font-library", Kind.LIBRARY),
    SoftwareComponent("windows-gdi-graphics-component", Kind.LIBRARY),
    SoftwareComponent("windows-group-policy-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-http-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ike-extension", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-imaging-component", Kind.LIBRARY),
    SoftwareComponent("windows-imaging-component-mscms-color-management", Kind.LIBRARY),
    SoftwareComponent("windows-ime", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-installer-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-internet-connection-sharing-ics-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ip-helper-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ip-routing-snapin", Kind.APPLICATION),
    SoftwareComponent("windows-iscsi-discovery-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-iscsi-target", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-isns-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-kdc-proxy-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-kerberos", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-kernel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-kernel32", Kind.LIBRARY),
    SoftwareComponent("windows-kernel-cryptography-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-kernel-streaming-wow-thunk-service-driver-ks-sys", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ldap-client", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ldap-server", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-lpd-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-media", Kind.LIBRARY),
    SoftwareComponent("windows-miracast", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-msdtc", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-multipoint-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-native-wifi-miniport-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-netlogon", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-network-address-translation-nat-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-network-load-balancing", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-network-virtualization", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ntfs-filesystem-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ntlm-authentication-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ocsp-snapin", Kind.APPLICATION),
    SoftwareComponent("windows-ole", Kind.LIBRARY),
    SoftwareComponent("windows-partition-management-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-pdf-library", Kind.LIBRARY),
    SoftwareComponent("windows-peap", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-performance-data-helper-library", Kind.LIBRARY),
    SoftwareComponent("windows-presentation-foundation-wpf", Kind.LIBRARY),
    SoftwareComponent("windows-print-spooler", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-rdp-clipboard-virtual-channel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-refs-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-access-connection-manager-rasman-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-access-management-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-assistance", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-desktop-licensing-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-desktop-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-desktop-web-access", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-remote-registry-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-rich-text-edit", Kind.LIBRARY),
    SoftwareComponent("windows-rpc-runtime", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-rpcss", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-rras", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-runtime", Kind.RUNTIME_HOST),
    SoftwareComponent("windows-sapi", Kind.LIBRARY),
    SoftwareComponent("windows-search", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-secure-channel-schannel", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-security-account-manager-sam", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-security-center", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-server-network-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-server-remote-desktop-gateway", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-server-update-services", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-service-tracing", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-smartscreen", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-spnego-extended-negotiation-negoex-security-mechanism", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-standards-based-storage-management-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-storage-stack", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-synccontroller-component", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-task-scheduler-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-telephony-service-tapisrv", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-terminal", Kind.APPLICATION),
    SoftwareComponent("windows-text-services", Kind.LIBRARY),
    SoftwareComponent("windows-uniscribe", Kind.LIBRARY),
    SoftwareComponent("windows-upnp", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-urlmon", Kind.LIBRARY),
    SoftwareComponent("windows-usb-audio-class-system-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-user-profile-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-volume-manager-extension-driver", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-warp", Kind.LIBRARY),
    SoftwareComponent("windows-webbrowser-control", Kind.LIBRARY),
    SoftwareComponent("windows-webclient-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-wlan-autoconfig-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-workstation-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("windows-ws-discovery-service", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("wingup-generic-updater", Kind.APPLICATION),
    SoftwareComponent("winrar", Kind.APPLICATION),
    SoftwareComponent("winscp", Kind.APPLICATION),
    SoftwareComponent("wireshark", Kind.APPLICATION),
    SoftwareComponent("x86-cpu-with-amx-xfd-support", Kind.OS, OsSubtype.GPOS),
    SoftwareComponent("xmllint", Kind.APPLICATION),
    SoftwareComponent("xmlrpc-c", Kind.LIBRARY),
    SoftwareComponent("xorg-server", Kind.APPLICATION),
    SoftwareComponent("xslt-processing-engine", Kind.RUNTIME_HOST),
    SoftwareComponent("zlib", Kind.LIBRARY),
    SoftwareComponent("zoom-client", Kind.APPLICATION),
)
