"""Generate defs/def_components.py: one static catalog of software components.

Keyed by catalog display_id. Each value holds the display name, description,
catalog record id, and the two logic v2 tags (role, remediation_tag).

Inputs:
  defs/catalog-tagging.html          catalog records: display_id, name,
                                     description, record id, role
  defs/os_non_os_v3.2/confident.json OS / Non-OS / Ignore remediation tag
  defs/os_non_os_v3.2/rest.json      (same, lower confidence; one set)
  db/cve_to_prereq_with_ids.csv      record id per display_id (`id` column)
  defs/def_eol.py                    endoflife.date slug and discontinued flag

Run again whenever an input changes:
  python3 scripts/build_def_components.py
"""

from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from defs.def_eol import DISCONTINUED, EOL_SLUGS  # noqa: E402
DEFS = ROOT / "defs"
CATALOG_HTML = DEFS / "catalog-tagging.html"
TAG_FILES = (
    DEFS / "os_non_os_v3.2" / "confident.json",
    DEFS / "os_non_os_v3.2" / "rest.json",
)
PREREQ_CSV = ROOT / "db" / "cve_to_prereq_with_ids.csv"
OUTPUT = DEFS / "def_components.py"

# Tagged components that have no record in the catalog export.
EXTRA_DESCRIPTIONS = {
    "Apache Axis2": "Apache Axis2/Java web-services engine (SOAP/XML stack) that can "
    "run as a web application inside a servlet container.",
}

# Strict role semantics: only these catalog roles are "the OS itself".
ROLE_BY_CATALOG_ROLE = {"os": "OS", "firmware": "FIRMWARE"}
TAG_BY_ANSWER = {"OS": "OS", "Non-OS": "NON_OS", "Ignore": "IGNORE"}


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.casefold()).strip("-")


def load_catalog() -> dict[str, dict]:
    """Catalog records keyed by display name."""
    html = CATALOG_HTML.read_text(encoding="utf-8")
    start = html.index("const D=") + len("const D=")
    data, _ = json.JSONDecoder().raw_decode(html[start:])
    return {record["name"]: record for record in data["records"]}


def load_tags() -> dict[str, dict]:
    """Remediation tag rows keyed by component display name."""
    rows: dict[str, dict] = {}
    for path in TAG_FILES:
        for row in json.loads(path.read_text(encoding="utf-8")):
            rows[row["component"]] = row
    return rows


def load_record_ids() -> dict[str, str]:
    """Catalog record id per display_id, from the software_component rows."""
    ids: dict[str, str] = {}
    with PREREQ_CSV.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            if row["type"] != "software_component" or not row.get("id"):
                continue
            known = ids.setdefault(row["display_id"], row["id"])
            if known != row["id"]:
                raise ValueError(f"{row['display_id']}: two record ids ({known}, {row['id']})")
    return ids


HEADER = '''"""Static catalog of software components, keyed by catalog display_id.

GENERATED by scripts/build_def_components.py. Do not edit by hand; change the
inputs (defs/catalog-tagging.html, defs/os_non_os_v3.2/*.json,
db/cve_to_prereq_with_ids.csv, defs/def_eol.py) and regenerate.

Two independent tags (logic v2):
  role             is the component the whole OS or firmware itself?
                   OS / FIRMWARE come from the catalog roles `os` and `firmware`
                   (strict: os-kernel, os-service, ... are OTHER).
  remediation_tag  is the component fixed by an OS / firmware update (OS),
                   by its own vendor patch (NON_OS), or not processed (IGNORE).
"""

from dataclasses import dataclass
from enum import Enum


class Role(Enum):
    """Catalog role, reduced to what the engine decides on.

    OS        the whole operating system (fixed by an OS update)
    FIRMWARE  device firmware or appliance OS (fixed by a firmware update)
    OTHER     everything else; routed by its remediation tag
    """

    OS = "os"
    FIRMWARE = "firmware"
    OTHER = "other"


class RemediationTag(Enum):
    """How a component is fixed."""

    OS = "OS"
    NON_OS = "Non-OS"
    IGNORE = "Ignore"


@dataclass(frozen=True, slots=True)
class SoftwareComponent:
    """One catalog component.

    catalog_record_id  catalog record uuid
    display_id         catalog display id; prerequisite files refer to it
    display_name       catalog display name
    description        catalog description
    catalog_role       the catalog's own role (os-kernel, application, ...)
    role               reduced role (see Role)
    remediation_tag    OS / NON_OS / IGNORE; None when untagged
    eol_slug           endoflife.date product slug; None when not on the site
    discontinued       end-of-life with no successor: remove, do not upgrade
    """

    catalog_record_id: str
    display_id: str
    display_name: str
    description: str
    catalog_role: str | None
    role: Role
    remediation_tag: RemediationTag | None
    eol_slug: str | None
    discontinued: bool

    @property
    def name(self) -> str:
        """Catalog display name (same as display_name)."""
        return self.display_name


SOFTWARE_COMPONENTS: dict[str, SoftwareComponent] = {
'''


def main() -> None:
    catalog = load_catalog()
    tags = load_tags()
    record_ids = load_record_ids()
    names = sorted(set(catalog) | set(tags), key=str.casefold)
    entries: dict[str, str] = {}
    from_csv = from_catalog = 0
    for name in names:
        record = catalog.get(name)
        row = tags.get(name)
        display_id = record["did"] if record else slug(name)
        if display_id in entries:
            raise ValueError(f"duplicate display_id {display_id}")
        record_id = record_ids.get(display_id)
        if record_id:
            from_csv += 1
            if record and record_id != record["id"]:
                raise ValueError(f"{name}: CSV id {record_id} differs from catalog id {record['id']}")
        elif record:
            record_id = record["id"]  # same id; this display_id is not in the CSV
            from_catalog += 1
        else:
            raise ValueError(f"{name}: no catalog record and no record id in the CSV")
        description = (record or {}).get("desc") or EXTRA_DESCRIPTIONS.get(name)
        if description is None:
            raise ValueError(f"{name}: no description")
        catalog_role = record["role"][0] if record else None
        role = ROLE_BY_CATALOG_ROLE.get(catalog_role or "", "OTHER")
        tag = TAG_BY_ANSWER.get(row["answer"]) if row else None
        entries[display_id] = (
            f"    {display_id!r}: SoftwareComponent(\n"
            f"        catalog_record_id={record_id!r},\n"
            f"        display_id={display_id!r},\n"
            f"        display_name={name!r},\n"
            f"        description={description.strip()!r},\n"
            f"        catalog_role={catalog_role!r},\n"
            f"        role=Role.{role},\n"
            f"        remediation_tag={('RemediationTag.' + tag) if tag else None},\n"
            f"        eol_slug={EOL_SLUGS.get(display_id)!r},\n"
            f"        discontinued={display_id in DISCONTINUED!r},\n"
            f"    ),\n"
        )
    unknown = (set(EOL_SLUGS) | set(DISCONTINUED)) - set(entries)
    if unknown:
        raise ValueError(f"def_eol.py names unknown display_ids: {sorted(unknown)}")
    body = "".join(entries[key] for key in sorted(entries))
    OUTPUT.write_text(HEADER + body + "}\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(entries)} components "
          f"({len(catalog)} in catalog, {len(tags)} tagged); record ids: "
          f"{from_csv} from the prerequisite CSV, {from_catalog} from the catalog export")


if __name__ == "__main__":
    main()
